import { Injectable } from '@nestjs/common';

@Injectable()
export class FilterService {
  private crimeDictionary = [
    'Roubo',
    'Roubo',
    'Roubado',
    'Roubada',
    'Furto',
    'Furto',
    'Furtado',
    'Furtada',
    'Batedor de carteira',
    'Trombadinha',
    'Assalto',
    'Assalto',
    'Assaltada',
    'Assaltado',
    'Arrastão',
    'Feminicídio',
    'Feminicídio',
    'Estupro',
    'Estupro',
    'Estuprado',
    'Estuprada',
    'Violentado',
    'Violentada',
    'Violência sexual',
    'Abuso sexual',
    'Abusada',
    'Abusado',
    'Importunação sexual',
    'Extorsão',
    'Extorsão',
    'Coagido',
    'Coagir',
    'Lesão Corporal',
    'Lesão Corporal',
    'Briga',
    'Confronto',
    'Agressão',
    'Agredida',
    'Agredido',
    'Confusão',
    'Violência doméstica',
    'Sequestro',
    'Sequestro',
    'Perseguição',
    'Homicídio',
    'Homicídio',
    'Assassinado',
    'Assassinada',
    'Tráfico de Drogas',
    'Tráfico de Drogas',
    'Tráfico',
    'Drogas',
    'Maconha',
    'Entorpecente',
    'Cocaína',
    'LSD',
    'Ecstasy',
    'Heroína',
    'Vítimas',
    'Vítimas',
    'Baleado',
    'Baleada',
    'Polícia',
    'Polícia',
    'Policial',
    'Camburão',
    'Viatura',
    'Depredação',
    'Depredação',
    'Pichações',
    'Pichação',
    'Vandalismo',
    'Vandalização',
    'Incêndio',
    'Incêndio',
    'Incêndia',
    'Incendiou',
    'Incendiaram',
  ];

  containsCrime(text: string): string {
    for (const keyword of this.crimeDictionary) {
      if (text.toLowerCase().includes(keyword.toLowerCase())) {
        return keyword.toLowerCase();
      }
    }
    return undefined;
  }
}
